---
title: "Tutorial: Using Analytic Hierarchy Process to define score weights"
author: "UNHCR MENA"
date: "Amman, `r format(Sys.Date(),  '%d %B %Y')`"
output: 
  slidy_presentation: 
    css: css/slidy-unhcr.css
    footer: UNHCR
    highlight: kate
    logo: img/UNHCR_logo-sq-big.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Defining weights through expert judgment 
- How expert can come up with values for the weight? 
- How to reach agreement among expert on the suggested values? 
- Is there an alternative to lenghty consensus building? 


## Use case with the Scoring Vulnerability 

Vulnerability is not observed, it's a latent variable, an intellectual construction based on multiple - criteria 

The challenge is: 

- Define the criteria  
- Define relative weight to be used for each criteria 

## The analytic hierarchy process (AHP)
- Structured technique for organizing and analysing complex decisions, based on mathematics and psychology 
- Comprehensive and rational framework to organise feeling, intuition & logic for structuring group decision making 
- Comparison is made between 2 alternatives based on decision-maker’s feeling of priority dues to importance, preference and likelihood of influence 
- Developed in the 70’s by Thomas Saaty

## Limitation of AHP 

- Assume a minimum level of judgement consistency among experts

- Limited number of criteria to minimise the numer of pairwise comparison estimation -  N*(N-1)/2 pairs to review: _5 criteria -> 10 comparisons, 6 criteria -> 15 comparison, 7 criteria -> 24 comparisons, 8 criteria -> 28 comparisons, 9 criteria -> 36 comparisons_

- Data should be available for all criteria

- The approach assumes that when new alternatives are added to a decision problem, the ranking of the old alternatives must not change 


## How to? A step by step approach

1. Define vulnerability criteria
2. Build the expert consultation form
3. Generate the AHP file from the collected data
4. Run AHP algorythm
5. Review results
6. Apply the formula



## 1. Define vulnerability criteria

- List potential criteria that would contribute to vulnerability within the current context 

- Establish treehold for criteria so that they can be formulated as simple binary questions

for instance, the following criteria can be saved in a csv file.

criteria code | criteria label 
------------- | -------------------------------------
age           | Age of head of household is above 50 
gender        | Gender of head of household is female
size          | Household size is above 5
needs         | Occurrence of Specific needs
assitance     | Do not Receive assistance

## 2. Build the expert consultation form

A form will allow to collect from expert priorities between criteria by making a series of judgments based on pairwise comparisons 
- Collect judgment for all pairwise comparison and each expert
- Ranking Scales for Criteria

Use the function ```1-Build-xlsform.R``` to build a [xlsform file](http://xlsform.org) based on criteria defined above.

The form can be used within [UNHCR Kobo server](httpp://kobo.unhcr.org)



## 3. Generate the AHP file from the collected data


Once collected from exprt (aka. decision-makers), data can be exported from [UNHCR Kobo server](httpp://kobo.unhcr.org) in csv format.

Use the function ```2-build-hierarchy.R``` to build a [xlsform file](http://xlsform.org) to create the [AHP file](https://cran.r-project.org/web/packages/ahp/vignettes/file-format.html).

This create the file recording the pairwise preferences of each decision-makers


## 4.  Run AHP algorythm
- Calculation done using [R statistical language](https://rpubs.com/gluc/ahp)
- Synthesize these judgments to yield a set of overall priorities
- Check judgments consistency (consistency ratio)
- Compute weights for each expert
- Mathematical calculations to convert these judgments to priorities for each of the four criteria

## 5. Review results

Knit the ```3-final-report.Rmd``` to get the report

- Lack of consistency is often observed 

- If __consistency ratio is above 0.1__, then judgement are untrustworthy because they are too close to randomness -> exercise needs to be repeated or abandonned.

## 6. Apply the formula
- Calculate mean relative weight
- Apply the vulnerability formula
- Collect data on each criteria for all household
- Apply weight to each record for the different criteria to get the vulnerability level of each household


 
 

