---
title: "Analytic Hierarchy Process Criteria Ranking"
date: "`r format(Sys.Date(),  '%d %B %Y')`"
output:
  html_document: 
    toc: yes
    toc_depth: 2
params:
  ahpFile: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(R6)
library(data.tree)
library(ahp)

processedAHP <- Load(params$ahpFile)

```

# Introduction


# Criteria 
The following criteria were compared through pairwise importance analysis 

```{r criteria, echo=FALSE, warning=FALSE, cache=FALSE, tidy = TRUE, message=FALSE, comment = "", fig.height=4, size="small"}

print(processedAHP, filterFun = isNotLeaf)

```

# Visualize the  model  

```{r visu, echo=FALSE, warning=FALSE, cache=FALSE, tidy = TRUE, message=FALSE, comment = "", fig.height=4, size="small"}

#print(processedAHP, filterFun = isNotLeaf)

Calculate(processedAHP)
#print(processedAHP, priority = function(x) x$parent$priority["Total", x$name])

Visualize(processedAHP)


```


# Output model analysis

```{r model, echo=FALSE, warning=FALSE, cache=FALSE, tidy = TRUE, message=FALSE, comment = "", fig.height=4, size="small"}

#Analyze(processedAHP)
AnalyzeTable(processedAHP)

```
